# Generated by Django 5.2 on 2025-04-20 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('ip', models.CharField(max_length=50)),
                ('accion', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'bitacora',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TokenDispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_fcm', models.TextField(unique=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='usuarios.usuarios')),
            ],
            options={
                'db_table': 'tokenNotf',
                'managed': True,
            },
        ),
    ]
